services:
  mail:
    image: postfix
    command: bash -c "echo ${DOMAIN} > /etc/mailname && \
                      echo virtual_alias_domains = ${DOMAIN} >> /etc/postfix/main.cf && \
                      echo virtual_alias_maps = hash:/etc/postfix/virtual >> /etc/postfix/main.cf && \
                      echo ${FORWARD_FROM} ${FORWARD_TO} > /etc/postfix/virtual && \
                      postmap /etc/postfix/virtual && \
                      service postfix restart && \
                      tail -f /dev/null"
    ports:
      - "25:25"
    restart: always